import java.io.*;
import java.util.*;

public class RooftopSolarEnergy {
    private String[] panelNames = { "Panel-A", "Panel-B", "Panel-C", "Panel-D", "Panel-E" };
    private double[] energyGenerated = { 6.5, 8.2, 5.8, 7.4, 9.1 };

    public void processText() {
        String projectName = "Rooftop Solar Energy System";
        System.out.println("Project Name: " + projectName);
        System.out.println("Project Name in Uppercase: " + projectName.toUpperCase());
        System.out.println("Project Name in Lowercase: " + projectName.toLowerCase());
        System.out.println("Length of Project Name: " + projectName.length());

        if (projectName.contains("Solar")) {
            System.out.println("Search Result: 'Solar' found in project name.");
        } else {
            System.out.println("Search Result: 'Solar' not found.");
        }
    }

    public void createReport() {
        StringBuilder report = new StringBuilder();
        report.append("\n===== SOLAR ENERGY REPORT =====\n");
        report.append("Project: Rooftop Solar Energy\n");
        report.append("Roof Area: 120 sq.m\n");
        report.append("Panel Efficiency: 20%\n");
        report.append("Number of Panels: 12\n");
        report.append("Sunlight Hours: 5.5 hours/day\n");
        report.append("================================\n");
        System.out.println(report);
    }

    public void sortEnergyData() {
        double[] sortedEnergy = energyGenerated.clone();
        Arrays.sort(sortedEnergy);
        System.out.println("\nEnergy Generated by Panels - Sorted:");
        for (double energy : sortedEnergy) {
            System.out.println(energy + " units");
        }

        double highest = sortedEnergy[sortedEnergy.length - 1];
        double lowest = sortedEnergy[0];
        System.out.println("\nHighest Energy Generated: " + highest + " units");
        System.out.println("Lowest Energy Generated: " + lowest + " units");
        if (highest > lowest) {
            System.out.println("Comparison: Highest generation is greater than lowest generation.");
        }
    }

    public void searchPanel(String panelName) {
        boolean found = false;
        for (int i = 0; i < panelNames.length; i++) {
            if (panelNames[i].equalsIgnoreCase(panelName)) {
                System.out.println("\nPanel Search Result:");
                System.out.println(panelNames[i] + " generates " + energyGenerated[i] + " units/day.");
                found = true;
                break;
            }
        }
        if (!found) {
            System.out.println("\nPanel " + panelName + " was not found.");
        }
    }

    public void writeToFile() {
        try {
            FileWriter writer = new FileWriter("SolarEnergyReport.txt");
            writer.write("ROOFTOP SOLAR ENERGY REPORT\n");
            writer.write("===========================\n");
            writer.write("Roof Area: 120 sq.m\n");
            writer.write("Panel Efficiency: 20%\n");
            writer.write("Number of Panels: 12\n");
            writer.write("Sunlight Hours: 5.5 hours/day\n\n");
            writer.write("Panel Energy Details:\n");
            for (int i = 0; i < panelNames.length; i++) {
                writer.write(panelNames[i] + " : " + energyGenerated[i] + " units/day\n");
            }
            writer.close();
            System.out.println("\nData successfully written to SolarEnergyReport.txt");
        } catch (IOException e) {
            System.out.println("Error while writing file: " + e.getMessage());
        }
    }

    public void readFromFile() {
        try {
            FileReader reader = new FileReader("SolarEnergyReport.txt");
            BufferedReader bufferedReader = new BufferedReader(reader);
            String line;
            System.out.println("\n===== DATA READ FROM FILE =====");
            while ((line = bufferedReader.readLine()) != null) {
                System.out.println(line);
            }
            bufferedReader.close();
        } catch (IOException e) {
            System.out.println("Error while reading file: " + e.getMessage());
        }
    }

    public static void main(String[] args) {
        RooftopSolarEnergy solar = new RooftopSolarEnergy();
        System.out.println("======================================");
        System.out.println("  ROOFTOP SOLAR ENERGY SYSTEM");
        System.out.println("======================================");

        solar.processText();
        solar.createReport();
        solar.searchPanel("Panel-C");
        solar.sortEnergyData();
        solar.writeToFile();
        solar.readFromFile();

       
    }
}
